export const ACT_SUBMIT_EMAIL = 'ACT_SUBMIT_EMAIL';

export const ACT_SUBMIT_CURRENCIES = 'ACT_GET_RESPONSE_API';

export const ACT_SUBMIT_EXPENSES = 'ACT_SUBMIT_EXPENSES';

export const ACT_SUM_EXPENSES = 'ACT_SUM_EXPENSES';
