export const ACT_SUBMIT_EMAIL = 'ACT_SUBMIT_EMAIL';

export const ACT_SUBMIT_CURRENCIES = 'ACT_GET_RESPONSE_API';

export const ACT_SUBMIT_EXPENSES = 'ACT_SUBMIT_EXPENSES';

export const ACT_DELETE_BTN = 'ACT_DELETE_BTN';

export const ACT_EDIT_BTN = 'ACT_EDIT_BTN';

export const ACT_CHECK_EDIT_BTN = 'ACT_CHECK_EDIT_BTN';
